### PR TITLE
ConstValueDist Tests

### PR DESCRIPTION
**Pull request by sthayashi**

### CODE REVIEW

**Comment by sthayashi** [comment]
- [ ] Cleanup code
- [x] Add sampler test
- [x] Fix unexpected behavior?
For example, is it expected that this works?
```
univariate_cvd = ConstValueDist( (a=Normal(),) )
fill_array_of_normal_dists = rand(univariate_cvd, 10^5)
```

**Comment by sthayashi** [comment]
Test for [`Distributions.quantile`](https://github.com/oschulz/ValueShapes.jl/blob/37878f08024b06a9c530f3080c71ad319a736c08/src/const_value_dist.jl#L46) not added. Not sure if it will change in the future.

**Comment by oschulz** [comment]
Is this ready to be merged?

**Comment by sthayashi** [comment]
Yes

**Pull request closed without merging**
